import Head from 'next/head'
import {Header} from '../components/Header'
import {SubHeader} from '../components/SubHeader'
import {PlanSection} from '../components/Section/PlanSection'
import {CostSection} from '../components/Section/CostSection'
import {Grid} from '@material-ui/core'
import { GridItem } from '@/components/Containers'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{maxWidth:'1440px', margin: '0 auto'}}>
        <Grid container >
          <GridItem>
            <Header/>
          </GridItem>
          <GridItem>
            <SubHeader/>
          </GridItem>
          <GridItem>
            <PlanSection/>
          </GridItem>
          <GridItem>
            <CostSection/>
          </GridItem>
        </Grid>
        
      </main>
    </>
  )
}
