import Head from 'next/head'
import { Montserrat, Open_Sans } from '@next/font/google'
import {Header} from '../components/Header'
import {SubHeader} from '../components/SubHeader'
import {PlanSection} from '../components/Section/PlanSection'
import {CostSection} from '../components/Section/CostSection'
import {Grid} from '@material-ui/core'

const montserrat = Montserrat({ subsets: ['latin'] })
const openSans = Open_Sans({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${montserrat.className} ${openSans.className}`} style={{maxWidth:'1440px'}}>
        <Grid container >
          <Grid item xs={12}>
            <Header/>
          </Grid>
          <Grid item xs={12}>
            <SubHeader/>
          </Grid>
          <Grid item xs={12}>
            <PlanSection/>
          </Grid>
          <Grid item xs={12}>
            <CostSection/>
          </Grid>
        </Grid>
        
      </main>
    </>
  )
}
